version: '3.5'

services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./flask:/usr/src/app"
        tty: true
        command: "./run.sh"
        stdin_open: true
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./redis:/data"
