version: '3.5'

services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - "./flask:/usr/src/app"
        tty: true
        stdin_open: true
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
            - "./redis:/data"
